### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by UnicodeAlt255** [ronny3050/PrimateFaceRecognition#2]
Could you please provide a a requirements list with `pip freeze`? It's not immediately obvious that scipy, scikit-learn, PIL, etc. are required, and which versions are required would be nice.

For example, the code base uses [`scipy.misc.imread`](https://github.com/ronny3050/PrimateFaceRecognition/blob/master/utils.py#L444) which has been deprecated and [removed](https://github.com/scipy/scipy/blob/9bdc2073fa2afd820f2eefbf11675d70a6d0eb2f/doc/release/1.3.0-notes.rst#scipyinterpolate-changes). I would like to contribute to update the use of scipy, but I would first like to know the exact requirements to avoid any more similar issues beforehand.

**Comment by ronny3050** [comment]
Hi! Thank you so much for your helpful suggestions. I have updated the readme along with a requirements.txt file which can be installed on top of a conda environment (easier for tensorflow).

Closing this issue -- I look forward to your pull request.
