### ISSUE TITLE
LemurFace dataset location

### ISSUE THREAD

**Issue by orlandokj** [ronny3050/PrimateFaceRecognition#3]
In the paper I read that the LemurFace dataset was in this repository, but I can't find it. It is in another place?
Maybe we can put the location of the dataset on the readme.

**Comment by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [comment]
Yeah, I think the README is pretty lacking right now, it would be great to have better documentation.

**Comment by ronny3050** [comment]
I will be updating the documentation and provide the dataset in the coming week. I appreciate your patience and thank you for your interest.

**Comment by sadda** [comment]
Hello, the link for the dataset seems to be still missing. Is there any chance to add it? Thanks a lot :)
